name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Install system build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r site/requirements.txt

    - name: Build the book
      run: |
        if [ ! -f site/_toc.yml ]; then
          jupyter-book toc from-project site -e .md -e .ipynb > site/_toc.yml
        fi
        jupyter-book build site
